const $=(q)=>document.querySelector(q);let adminData=null;
function key(){return $("#adminKey").value.trim()||sessionStorage.getItem("slovasyans-admin-key")||""}
async function requestAdmin(path="",options={}){const k=key();if(!k)throw new Error("Введи ADMIN_SECRET");sessionStorage.setItem("slovasyans-admin-key",k);const r=await fetch(`/api/admin${path}`,{...options,headers:{"Content-Type":"application/json","x-admin-key":k,...(options.headers||{})},cache:"no-store"});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||data.error||`HTTP ${r.status}`);return data}
function render(data){adminData=data;$("#adminPanel").hidden=false;$("#adminSummary").innerHTML=`<div><b>${data.profiles??data.repaired??0}</b><br><span>облачных профилей</span></div><div><b>${data.leaderboardRecords??data.players?.length??0}</b><br><span>записей лидерборда</span></div>${data.deduped!=null?`<div><b>${data.deduped}</b><br><span>дублей удалено</span></div>`:""}`;$("#adminPlayers").innerHTML=(data.players||[]).map(p=>`<tr><td>${escapeHtml(p.name||"Игрок")}</td><td>${escapeHtml(p.id||"")}</td><td>${p.levels||0}</td><td>${p.stars||0}</td><td>${p.duels??p.duel??0}</td></tr>`).join("")}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function refresh(){$("#adminStatus").textContent="Загружаю…";try{const d=await requestAdmin();render(d);$("#adminStatus").textContent="Данные актуальны"}catch(e){$("#adminStatus").textContent=e.message;$("#adminStatus").classList.add("danger")}}
$("#adminConnect").onclick=refresh;$("#adminRefresh").onclick=refresh;
$("#adminRepair").onclick=async()=>{if(!confirm("Пересчитать уровни, звёзды и синхронизировать лидерборды для всех профилей?"))return;$("#adminStatus").textContent="Пересчитываю…";try{const d=await requestAdmin("",{method:"POST",body:JSON.stringify({action:"repair_all"})});render(d);$("#adminStatus").textContent=`Готово: профилей ${d.repaired}, уровней исправлено ${d.levelsChanged}, звёзд ${d.starsChanged}, дублей ${d.deduped}`;}catch(e){$("#adminStatus").textContent=e.message}};
$("#adminDedupe").onclick=async()=>{$("#adminStatus").textContent="Ищу дубли…";try{const d=await requestAdmin("",{method:"POST",body:JSON.stringify({action:"dedupe"})});$("#adminStatus").textContent=`Удалено дублей: ${d.deduped}`;await refresh()}catch(e){$("#adminStatus").textContent=e.message}};
const saved=sessionStorage.getItem("slovasyans-admin-key");if(saved){$("#adminKey").value=saved;refresh()}
