import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';

const source=await readFile(new URL('../js/narrative/story-encounter-routing.js',import.meta.url),'utf8');
const definitions=JSON.parse(await readFile(new URL('../content/worlds/forest/v0.03/data/encounters.json',import.meta.url),'utf8'));
const presentation=JSON.parse(await readFile(new URL('../content/worlds/forest/v0.03/data/encounter-presentation.json',import.meta.url),'utf8'));
function load(){const s={console};s.globalThis=s;vm.runInNewContext(source,s);return s.SolivocStoryEncounterRouting;}
const router=load();
const M=['cat','owl','fox'];
function outcomeFor(variantId){return presentation.variants?.[variantId]?.outcome||presentation.fixedEncounters?.[variantId]?.outcome||{};}
function rng(seed){let x=seed|0;return()=>{x=(x*1664525+1013904223)|0;return (x>>>0)/4294967296}}
function init(){const rel={};for(const c of M)rel[c]={identityKnown:c!=='fox',acquainted:c!=='fox',meaningfulRelationshipEvents:c==='fox'?0:2,milestones:{}};return {rel,lastInitiative:{cat:0,owl:0,fox:0},lastEncounter:{cat:4,owl:4,fox:0},questions:{cat:[],owl:[],fox:[]},completed:[],selected:{},recent:[],history:[]}}
function pickDirectChoices(state,random,upto){const choices=[[5,['cat','owl',null,null]],[8,['cat','owl',null]],[10,['cat','owl',null,null]],[12,['cat','owl',null,null]],[25,[null,'cat',null,null]],[53,[null,null,'cat',null]]];for(const [level,opts] of choices){if(level>upto||state.choiceLevels?.has(level))continue;(state.choiceLevels??=new Set).add(level);const c=opts[Math.floor(random()*opts.length)];if(c)state.lastInitiative[c]=level;}}
function snapshot(s){const threads={};for(const c of M)threads[c]={freshVoluntaryContinuation:s.lastInitiative[c]>s.lastEncounter[c],unresolvedQuestionKeys:[...s.questions[c]],unfinishedQuestion:s.questions[c].length>0};return {relationships:s.rel,threads,recentEncounterParticipants:[...s.recent]};}
function apply(s,enc,decision){const v=enc.variants.find(x=>x.id===decision.selectedVariant);s.selected[enc.id]=v.id;s.completed.push(enc.id);s.history.push({encounterId:enc.id,participants:[...v.participants],reasons:[...decision.reasons]});s.recent.push(...v.participants);s.recent=s.recent.slice(-6);for(const c of v.participants){if(!M.includes(c))continue;const r=s.rel[c];r.identityKnown=true;r.acquainted=true;r.meaningfulRelationshipEvents+=2;const authored=outcomeFor(v.id);for(const m of authored.ensureMilestones||[]){if(!r.milestones[m]){r.milestones[m]=true;r.meaningfulRelationshipEvents+=1}}if(authored.temporaryAlliance===true){if(!r.milestones.temporary_alliance_completed){r.milestones.temporary_alliance_completed=true;r.meaningfulRelationshipEvents+=2}}s.lastEncounter[c]=enc.window[1];if(v.opensUnresolvedQuestionKey&&!s.questions[c].includes(v.opensUnresolvedQuestionKey))s.questions[c].push(v.opensUnresolvedQuestionKey);if(enc.id==='ENC_FOREST_09'&&r.milestones.cooperation_established)r.narrativeCompatibility=true;}}
function run(seed){const random=rng(seed),s=init();for(const enc of definitions.encounters.filter(e=>Number(e.id.slice(-2))>=2&&Number(e.id.slice(-2))<=10)){pickDirectChoices(s,random,enc.window[0]);let decision=null;for(let level=enc.window[0];level<=enc.window[1];level++){const d=router.routeEncounter({encounter:enc,level,snapshot:snapshot(s),completedEncounterIds:s.completed});if(d.status==='selected'){decision=d;break}if(['p0-no-eligible-variant','deadline-unresolved'].includes(d.status)&&level===enc.window[1])return {ok:false,reason:d.status,encounter:enc.id,state:s};}if(!decision)return {ok:false,reason:'no-selection',encounter:enc.id,state:s};if(enc.id==='ENC_FOREST_10'){const c=decision.participants[0];s.rel[c].milestones.relationship_synthesis_completed=true;s.rel[c].milestones.companion=true;s.companion=c;s.selected[enc.id]=decision.selectedVariant;s.completed.push(enc.id);s.history.push({encounterId:enc.id,participants:[...decision.participants],reasons:[...decision.reasons]});return {ok:true,state:s}}apply(s,enc,decision);}return {ok:false,reason:'no-e10',state:s};}

test('10k deterministic Forest relationship graphs have no E2-E10 dead end and all first companions are reachable',()=>{
 const totals={cat:0,owl:0,fox:0},encounters={},failures=[];let e8Missing=0,e10Missing=0,tripleSolo=0;const tripleSamples=[];
 for(let seed=1;seed<=10000;seed++){const result=run(seed);if(!result.ok){failures.push({seed,reason:result.reason,encounter:result.encounter});continue}const s=result.state;totals[s.companion]++;for(const [id,v] of Object.entries(s.selected))(encounters[id]??={})[v]=(encounters[id][v]||0)+1;const eligible8=M.some(c=>s.rel[c].milestones.temporary_alliance_completed);if(!eligible8)e8Missing++;const eligible10=M.filter(c=>s.rel[c].milestones.cooperation_established&&s.rel[c].narrativeCompatibility);if(!eligible10.length)e10Missing++;for(let i=2;i<s.history.length;i++){const a=s.history[i-2].participants,b=s.history[i-1].participants,c=s.history[i].participants;if(Number(s.history[i].encounterId.slice(-2))<8&&a.length===1&&b.length===1&&c.length===1&&a[0]===b[0]&&b[0]===c[0]){tripleSolo++;if(tripleSamples.length<8)tripleSamples.push({seed,encounters:s.history.slice(i-2,i+1)});}}}
 console.log(JSON.stringify({runs:10000,companions:totals,failures:failures.slice(0,5),failureCount:failures.length,e8Missing,e10Missing,tripleSolo,tripleSamples,encounters},null,2));
 assert.equal(failures.length,0);assert.equal(e8Missing,0);assert.equal(e10Missing,0);assert.equal(tripleSolo,0);for(const c of M)assert.ok(totals[c]>0,`${c} companion unreachable`);
});
